spring:
  datasource:
    url: jdbc:mysql://localhost:3307/devdb
    username: root
    password: root00
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
